language: node_js

node_js:
  - "0.10"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - gem install bundler
  - bundle install
  - curl https://install.meteor.com | /bin/sh
  - npm install -g spacejam
  - meteor --version
  - phantomjs -v

script:
  - spacejam test-packages ./
