language: node_js
node_js:
  - "0.10"

git:
  submodules: false

before_install:
  # OS
  #- export DISPLAY=:99.0
  #- sh -e /etc/init.d/xvfb start

  # Meteor
  - curl https://install.meteor.com | /bin/sh

  # Git
  #- test -e .gitmodules && sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  #- git submodule update --init --recursive

  # Ruby
  - which bundle >/dev/null || gem install bundler
  #- bundle install

  # Npm
  - npm install -g coffee-script spacejam

  # Versions
  - ruby -v
  - bundle -v
  - meteor --version
  - phantomjs -v

script:
  - spacejam test-packages ./
